### ISSUE TITLE
No Website Logo?

### ISSUE THREAD

**Issue by elharony** [Tech-View/Website#2]
I know we aren't designers, but it would be great if we can come up with a basic logo to use on `TechView` GitHub Organization Page, and on the website!

It could be just the same title, with a design touch, here's an example:
![JavaScript Info](https://user-images.githubusercontent.com/16986422/66881361-e9684a80-efc6-11e9-8fe9-b6f246038739.jpg)

**Comment by islamCodehood** [comment]
Here are my proposals
![Tech View (5)](https://user-images.githubusercontent.com/16297114/66910607-25270280-f00f-11e9-9cda-3909525c7aa6.png)
![Tech View](https://user-images.githubusercontent.com/16297114/66910608-25bf9900-f00f-11e9-93b4-788d14c7cfcd.png)
![TechView2](https://user-images.githubusercontent.com/16297114/66910609-25bf9900-f00f-11e9-89dc-bfaadd293b3c.png)

**Comment by islamCodehood** [comment]
And with different colors:
![Tech View (1)](https://user-images.githubusercontent.com/16297114/66911062-13922a80-f010-11e9-8600-57964bba47bd.png)
![Tech View (2)](https://user-images.githubusercontent.com/16297114/66911064-142ac100-f010-11e9-902e-e13d0f570721.png)
![Tech View (3)](https://user-images.githubusercontent.com/16297114/66911067-14c35780-f010-11e9-98dd-9c3be31d2bb3.png)

**Comment by elharony** [comment]
I liked the 2nd Orange/Black one, great work @Islam888 !
What do you think, @MOhammedRiaad , @mohamednajiub ?

**Comment by MOhammedRiaad** [comment]
i go with the second orange on

**Comment by MOhammedRiaad** [comment]
![TechView](https://user-images.githubusercontent.com/33371146/66932764-64b61480-f038-11e9-9c52-088aed178de6.jpg)

**Comment by mohamednajiub** [comment]
> I liked the 2nd Orange/Black one, great work @Islam888 !
> What do you think, @MOhammedRiaad , @mohamednajiub ?

I think orange back ground and black text is great.

**Comment by mohamednajiub** [comment]
I think there is no need to make this issue still open, so if the final decision to choose the second logo "Orange background and the black text" close this issue @elharony

**Comment by elharony** [comment]
I tried to crop @Islam888 2nd logo, and I did an acceptable 350x350 picture as our Organization Profile Picture, but we still need a wider/smaller version (150x50) for example.

Can anyone do it guys?

**Comment by islamCodehood** [comment]
> I tried to crop @Islam888 2nd logo, and I did an acceptable 350x350 picture as our Organization Profile Picture, but we still need a wider/smaller version (150x50) for example.
> 
> Can anyone do it guys?

I can do it with PS tonight. I will see all the sizes we will need for favicons, logos, social medias, etc.

**Comment by mohamednajiub** [comment]
Hi, Guys,
these logos for different purposes,
![techview150_100](https://user-images.githubusercontent.com/22493564/68137220-494f7280-ff2f-11e9-8b07-a88e9fd21875.png)
![techView200_100](https://user-images.githubusercontent.com/22493564/68137258-5704f800-ff2f-11e9-8e5a-fa97cf2bda0f.png)

and here you can find favIcon
![favicon-96x96](https://user-images.githubusercontent.com/22493564/68138158-c62f1c00-ff30-11e9-9409-5584f9117c41.png)

**Comment by elharony** [comment]
Great job @mohamednajiub 👍 
Please upload the sized, final media files here. So that we start using them!

**Comment by mohamednajiub** [comment]
Thanks @elharony 
you can check the favicon and the logo with different colors [here](https://drive.google.com/open?id=176MQ1wD_rpBlw1PW1Sm5oklanITTDrUp)
