### ISSUE TITLE
Which Tech Stack to use?

### ISSUE THREAD

**Issue by elharony** [Tech-View/Website#3]
Let's discuss, which Stack/Tools are we going to use on `TechView`? No preferences here, but here are some notes to be considered:
- **Scalability I:** We are going to have MANY questions & answers around +300 Q&A, and the CRUD operation has to be done easily.
- **Scalability II:** Later on, we will add new topics (i.e. React, JavaScript, ... etc.). So, our approach **shouldn't** consider duplicating everything for each topic!
- **Budget:** Currently, we don't have a budget, but we could afford basic budget, so please don't consider any Paid Service/Tool right now.
- **Learning Curve:** The easier new developers can jump & add more questions, edit an existing one, the better. So, try to avoid non-necessary tools as possible as we could, and only go for well-documented tools/stack.

**Comment by islamCodehood** [comment]
I suggest : https://docusaurus.io/

 - Easily scalable, and easy to learn for new devs. 
- Open source.
- From Facebook
- Easy contribution by adding new content to an md file.
- Using React js for Theme building.

**Comment by mohamednajiub** [comment]
> I suggest : https://docusaurus.io/
> 
> * Easily scalable, and easy to learn for new devs.
> * Open source.
> * From Facebook
> * Easy contribution by adding new content to an md file.
> * Using React js for Theme building.

I think it's a great choice too because it was trusted by a lot of open-source projects like 'create-react-app' and so you can check their users [here](https://docusaurus.io/en/users) but also there are other features:

- Support localization.
- Easy to deploy. "it generates static HTML files so it can be hosted by Github pages which don't need any fees to use "

**Comment by elharony** [comment]
Great insights, @Islam888 , @mohamednajiub. Would love to hear your ideas, @MOhammedRiaad !

In terms of scaling the product; Do you think a file-based database would be a good idea? I mean, for React only we might have +300 questions. Which means, +300 files for React only.

What do you think?

**Comment by MOhammedRiaad** [comment]
i think we can start small and scale by time ,

**Comment by islamCodehood** [comment]
I would also go for starting small and scale by time, but thinking that we would have 300+ files for a single technology questions is terrifying. 
Do we really need a file for each single question? Can't we make an md single file for each tech? And then add same tech questions to the same file. For example,  react.md, javascript.md, etc.

**Comment by elharony** [comment]
Hmmm. It won't differ much, @Islam888 . Currently, the +300 React Interview Questions has +5000 lines!

**Comment by elharony** [comment]
We decided to start with Docusaurus 👍
