### ISSUE TITLE
Which kind of hosting?

### ISSUE THREAD

**Issue by islamCodehood** [Tech-View/Website#4]
Serverless, or server hosting and in either case which service we should use?

**Comment by islamCodehood** [comment]
I suggest going for _serverless_ hosting using **Netlify** with its ability for _live-deployment_ with every push to the github repo. With a free account we will have a bandwidth of 100GB. I think this would be more than enough for now. 
Things to take into consideration that with free account we will have only 1 team member who can make deploys.

Here is all the info for the free account https://www.netlify.com/pricing/

**Comment by elharony** [comment]
I agree with you. Especially, if we decided to use https://docusaurus.io, they work perfectly together I guess!

What do you think, @mohamednajiub , @MOhammedRiaad ?

**Comment by MOhammedRiaad** [comment]
i think we can go with netlify as it is also recomended by docusaurus.io

**Comment by mohamednajiub** [comment]
docusaurus is supporting all static hosting so we can use netlify or GitHub pages, it won't be an issue.

**Comment by islamCodehood** [comment]
> docusaurus is supporting all static hosting so we can use netlify or GitHub pages, it won't be an issue.

Yes, this is right, but because of it is easier to _build_ and  _deploy_ on netlify and there is a consensus on netlify, so let's do it there.
